#include "../include/web_server_private.h"
#include "esp_log.h"

static const char *TAG = "WEB_SERVER";


/* Simple HTML web page */
static const char *HTML_PAGE = "<!DOCTYPE html>\n"
"<html lang=\"uk\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Система керування електроживленням</title>\n"
"    <style>\n"
"        * {\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            box-sizing: border-box;\n"
"        }\n"
"        \n"
"        body {\n"
"            font-family: 'Arial', sans-serif;\n"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
"            min-height: 100vh;\n"
"            padding: 10px;\n"
"            color: #333;\n"
"        }\n"
"        \n"
"        .container {\n"
"            max-width: 500px;\n"
"            margin: 0 auto;\n"
"        }\n"
"        \n"
"        .header {\n"
"            text-align: center;\n"
"            color: white;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        \n"
"        .header h1 {\n"
"            font-size: 24px;\n"
"            margin-bottom: 5px;\n"
"        }\n"
"        \n"
"        .header p {\n"
"            font-size: 14px;\n"
"            opacity: 0.9;\n"
"        }\n"
"        \n"
"        .dashboard {\n"
"            display: grid;\n"
"            gap: 20px;\n"
"        }\n"
"        \n"
"        .card {\n"
"            background: rgba(255, 255, 255, 0.95);\n"
"            border-radius: 15px;\n"
"            padding: 20px;\n"
"            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\n"
"        }\n"
"        \n"
"        .card h2 {\n"
"            color: #333;\n"
"            margin-bottom: 15px;\n"
"            font-size: 18px;\n"
"            border-bottom: 2px solid #007bff;\n"
"            padding-bottom: 5px;\n"
"        }\n"
"        \n"
"        /* Моніторинг системи */\n"
"        .metrics-grid {\n"
"            display: grid;\n"
"            grid-template-columns: 1fr 1fr;\n"
"            gap: 15px;\n"
"        }\n"
"        \n"
"        .metric {\n"
"            text-align: center;\n"
"        }\n"
"        \n"
"        .metric label {\n"
"            display: block;\n"
"            font-size: 12px;\n"
"            color: #666;\n"
"            margin-bottom: 5px;\n"
"        }\n"
"        \n"
"        .metric span {\n"
"            font-size: 18px;\n"
"            font-weight: bold;\n"
"            color: #007bff;\n"
"        }\n"
"        \n"
"        .progress-bar {\n"
"            width: 100%;\n"
"            height: 6px;\n"
"            background-color: #e9ecef;\n"
"            border-radius: 3px;\n"
"            margin-top: 5px;\n"
"            overflow: hidden;\n"
"        }\n"
"        \n"
"        .progress {\n"
"            height: 100%;\n"
"            background: linear-gradient(90deg, #28a745, #ffc107, #dc3545);\n"
"            transition: width 0.3s ease;\n"
"        }\n"
"        \n"
"        /* Керування каналами */\n"
"        .channels-grid {\n"
"            display: grid;\n"
"            gap: 15px;\n"
"        }\n"
"        \n"
"        .channel-card {\n"
"            border: 2px solid #e9ecef;\n"
"            border-radius: 10px;\n"
"            padding: 15px;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        \n"
"        .channel-card.connected {\n"
"            border-color: #28a745;\n"
"            background-color: #f8fff9;\n"
"        }\n"
"        \n"
"        .channel-card.disconnected {\n"
"            border-color: #dc3545;\n"
"            background-color: #fff8f8;\n"
"        }\n"
"        \n"
"        .channel-card h3 {\n"
"            font-size: 16px;\n"
"            margin-bottom: 10px;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 10px;\n"
"        }\n"
"        \n"
"        .status-indicator {\n"
"            width: 12px;\n"
"            height: 12px;\n"
"            border-radius: 50%;\n"
"            display: inline-block;\n"
"        }\n"
"        \n"
"        .status-on {\n"
"            background-color: #28a745;\n"
"            box-shadow: 0 0 8px rgba(40, 167, 69, 0.6);\n"
"        }\n"
"        \n"
"        .status-off {\n"
"            background-color: #dc3545;\n"
"        }\n"
"        \n"
"        .channel-status {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            margin-bottom: 10px;\n"
"            font-size: 14px;\n"
"        }\n"
"        \n"
"        .power-consumption {\n"
"            font-weight: bold;\n"
"            color: #007bff;\n"
"        }\n"
"        \n"
"        .channel-controls {\n"
"            display: flex;\n"
"            gap: 10px;\n"
"        }\n"
"        \n"
"        .btn {\n"
"            flex: 1;\n"
"            padding: 8px 12px;\n"
"            border: none;\n"
"            border-radius: 5px;\n"
"            cursor: pointer;\n"
"            font-size: 12px;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        \n"
"        .btn-success {\n"
"            background-color: #28a745;\n"
"            color: white;\n"
"        }\n"
"        \n"
"        .btn-success:hover {\n"
"            background-color: #219a3c;\n"
"        }\n"
"        \n"
"        .btn-danger {\n"
"            background-color: #dc3545;\n"
"            color: white;\n"
"        }\n"
"        \n"
"        .btn-danger:hover {\n"
"            background-color: #c82333;\n"
"        }\n"
"        \n"
"        .btn-primary {\n"
"            background-color: #007bff;\n"
"            color: white;\n"
"        }\n"
"        \n"
"        .btn-secondary {\n"
"            background-color: #6c757d;\n"
"            color: white;\n"
"        }\n"
"        \n"
"        /* Конфігурація */\n"
"        .config-form {\n"
"            display: grid;\n"
"            gap: 15px;\n"
"        }\n"
"        \n"
"        .form-group {\n"
"            display: grid;\n"
"            gap: 5px;\n"
"        }\n"
"        \n"
"        .form-group label {\n"
"            font-weight: bold;\n"
"            font-size: 14px;\n"
"        }\n"
"        \n"
"        .form-group input, .form-group select {\n"
"            padding: 8px;\n"
"            border: 2px solid #e9ecef;\n"
"            border-radius: 5px;\n"
"            font-size: 14px;\n"
"        }\n"
"        \n"
"        .form-group small {\n"
"            color: #666;\n"
"            font-size: 12px;\n"
"        }\n"
"        \n"
"        .device-priority {\n"
"            display: grid;\n"
"            grid-template-columns: 1fr auto;\n"
"            gap: 10px;\n"
"            align-items: center;\n"
"            padding: 10px;\n"
"            background-color: #f8f9fa;\n"
"            border-radius: 8px;\n"
"        }\n"
"        \n"
"        .priority-high {\n"
"            background-color: #d4edda;\n"
"            border-left: 4px solid #28a745;\n"
"        }\n"
"        \n"
"        .priority-low {\n"
"            background-color: #f8d7da;\n"
"            border-left: 4px solid #dc3545;\n"
"        }\n"
"        \n"
"        .config-buttons {\n"
"            display: grid;\n"
"            grid-template-columns: 1fr 1fr;\n"
"            gap: 10px;\n"
"            margin-top: 20px;\n"
"        }\n"
"        \n"
"        .error-message {\n"
"            background-color: #f8d7da;\n"
"            color: #721c24;\n"
"            padding: 12px;\n"
"            border-radius: 8px;\n"
"            margin-bottom: 15px;\n"
"            border: 1px solid #ffc7c7;\n"
"        }\n"
"        \n"
"        .success-message {\n"
"            background-color: #d4edda;\n"
"            color: #155724;\n"
"            padding: 12px;\n"
"            border-radius: 8px;\n"
"            margin-bottom: 15px;\n"
"            border: 1px solid #c3e6cb;\n"
"        }\n"
"        \n"
"        @media (max-width: 480px) {\n"
"            .metrics-grid {\n"
"                grid-template-columns: 1fr;\n"
"            }\n"
"            \n"
"            .config-buttons {\n"
"                grid-template-columns: 1fr;\n"
"            }\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <div class=\"header\">\n"
"            <h1>Система керування електроживленням</h1>\n"
"            <p>Electroman</p>\n"
"        </div>\n"
"        \n"
"        <div class=\"dashboard\">\n"
"            <!-- Моніторинг системи -->\n"
"            <div class=\"card\">\n"
"                <h2>📊 Моніторинг системи</h2>\n"
"                <div class=\"metrics-grid\">\n"
"                    <div class=\"metric\">\n"
"                        <label>Напруга:</label>\n"
"                        <span id=\"voltage\">224</span> В\n"
"                        <div class=\"progress-bar\">\n"
"                            <div class=\"progress\" id=\"voltage-progress\" style=\"width: 95%\"></div>\n"
"                        </div>\n"
"                    </div>\n"
"                    <div class=\"metric\">\n"
"                        <label>Струм:</label>\n"
"                        <span id=\"current\">0.47</span> А\n"
"                    </div>\n"
"                    <div class=\"metric\">\n"
"                        <label>Потужність:</label>\n"
"                        <span id=\"power\">105</span> Вт\n"
"                        <div class=\"progress-bar\">\n"
"                            <div class=\"progress\" id=\"power-progress\" style=\"width: 95%\"></div>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"            \n"
"            <!-- Керування каналами -->\n"
"            <div class=\"card\">\n"
"                <h2>🎛️ Керування каналами</h2>\n"
"                <div class=\"channels-grid\">\n"
"                    <div class=\"channel-card connected\" id=\"channel-1\">\n"
"                        <h3>\n"
"                            <span class=\"status-indicator status-on\"></span>\n"
"                            Канал 1 - Лампа A\n"
"                        </h3>\n"
"                        <div class=\"channel-status\">\n"
"                            <span id=\"status-1\">Підключено</span>\n"
"                        </div>\n"
"                        <div class=\"channel-controls\">\n"
"                            <button class=\"btn btn-success\" onclick=\"toggleChannel(1, true)\">Увімкнути</button>\n"
"                            <button class=\"btn btn-danger\" onclick=\"toggleChannel(1, false)\">Вимкнути</button>\n"
"                        </div>\n"
"                    </div>\n"
"                    \n"
"                    <!-- <div class=\"channel-card disconnected\" id=\"channel-2\"> -->\n"
"                    <div class=\"channel-card connected\" id=\"channel-2\">\n"
"                        <h3>\n"
"                            <!-- <span class=\"status-indicator status-off\"></span> -->\n"
"                            <span class=\"status-indicator status-on\"></span>\n"
"                            Канал 2 - Лампа B\n"
"                        </h3>\n"
"                        <div class=\"channel-status\">\n"
"                            <span id=\"status-2\">Відключено</span>\n"
"                        </div>\n"
"                        <div class=\"channel-controls\">\n"
"                            <button class=\"btn btn-success\" onclick=\"toggleChannel(2, true)\">Увімкнути</button>\n"
"                            <button class=\"btn btn-danger\" onclick=\"toggleChannel(2, false)\">Вимкнути</button>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"            \n"
"            <!-- Конфігурація системи -->\n"
"            <div class=\"card\">\n"
"                <h2>⚙️ Конфігурація системи</h2>\n"
"                <div id=\"messages\"></div>\n"
"                <div class=\"config-form\">\n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"power-limit\">Гранична потужність (Вт):</label>\n"
"                        <input type=\"number\" id=\"power-limit\" min=\"50\" max=\"200\" value=\"100\" step=\"5\">\n"
"                        <small>При перевищенні цього значення активується алгоритм пріоритизації</small>\n"
"                    </div>\n"
"                    \n"
"                    <div class=\"form-group\">\n"
"                        <label for=\"reconnect-delay\">🔄 Час до спроби відновлення (сек):</label>\n"
"                        <input type=\"number\" id=\"reconnect-delay\" min=\"10\" max=\"300\" value=\"45\" step=\"5\">\n"
"                        <small>Скільки секунд чекати після відключення перед спробою увімкнути пристрій знову</small>\n"
"                    </div>\n"
"                    \n"
"                    <div class=\"form-group\">\n"
"                        <label>Налаштування пріоритетів пристроїв:</label>\n"
"                        \n"
"                        <div class=\"device-priority priority-high\">\n"
"                            <label for=\"device1-priority\">Лампа A (Канал 1):</label>\n"
"                            <select id=\"device1-priority\">\n"
"                                <option value=\"high\" selected>Високий пріоритет</option>\n"
"                                <option value=\"low\">Низький пріоритет</option>\n"
"                            </select>\n"
"                        </div>\n"
"                        \n"
"                        <div class=\"device-priority priority-low\">\n"
"                            <label for=\"device2-priority\">Лампа B (Канал 2):</label>\n"
"                            <select id=\"device2-priority\">\n"
"                                <option value=\"high\">Високий пріоритет</option>\n"
"                                <option value=\"low\" selected>Низький пріоритет</option>\n"
"                            </select>\n"
"                        </div>\n"
"                        \n"
"                        <small>При перевищенні граничної потужності спочатку відключаються пристрої з низьким пріоритетом</small>\n"
"                    </div>\n"
"                    \n"
"                    <div class=\"config-buttons\">\n"
"                        <button class=\"btn btn-primary\" onclick=\"saveSystemConfig()\">Зберегти конфігурацію</button>\n"
"                        <button class=\"btn btn-secondary\" onclick=\"resetToDefaults()\">Скинути до заводських</button>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        class PowerControlAPI {\n"
"            constructor() {\n"
"                this.baseUrl = window.location.origin;\n"
"                this.updateInterval = 1000;\n"
"                this.startAutoUpdate();\n"
"            }\n"
"            \n"
"            async getSystemStatus() {\n"
"                try {\n"
"                    const response = await fetch(`${this.baseUrl}/api/status`);\n"
"                    const data = await response.json();\n"
"                    this.updateUI(data);\n"
"                    return data;\n"
"                } catch (error) {\n"
"                    console.error('Помилка отримання статусу:', error);\n"
"                    // this.showError('Втрачено зв\\'язок з системою');\n"
"                }\n"
"            }\n"
"            \n"
"            async toggleChannel(channelId, state) {\n"
"                try {\n"
"                    const response = await fetch(`${this.baseUrl}/api/channel`, {\n"
"                        method: 'POST',\n"
"                        headers: { 'Content-Type': 'application/json' },\n"
"                        body: JSON.stringify({ channel: channelId, state: state })\n"
"                    });\n"
"                    const result = await response.json();\n"
"                    if (result.success) {\n"
"                        this.getSystemStatus(); // Оновити статус\n"
"                    }\n"
"                    return result;\n"
"                } catch (error) {\n"
"                    this.showError(`Помилка керування каналом ${channelId}`);\n"
"                }\n"
"            }\n"
"            \n"
"            async savePriorityConfig() {\n"
"                try {\n"
"                    const device1Priority = document.getElementById('device1-priority').value;\n"
"                    const device2Priority = document.getElementById('device2-priority').value;\n"
"                    const powerLimit = document.getElementById('power-limit').value;\n"
"                    const delayTime = document.getElementById('delay-before-disconnect').value;\n"
"                    const reconnectDelay = document.getElementById('reconnect-delay').value;\n"
"                    \n"
"                    const response = await fetch(`${this.baseUrl}/api/config`, {\n"
"                        method: 'POST',\n"
"                        headers: { 'Content-Type': 'application/json' },\n"
"                        body: JSON.stringify({ \n"
"                            device1_priority: device1Priority, \n"
"                            device2_priority: device2Priority,\n"
"                            power_limit: parseInt(powerLimit),\n"
"                            delay_time: parseInt(delayTime),\n"
"                            reconnect_delay: parseInt(reconnectDelay)\n"
"                        })\n"
"                    });\n"
"                    const result = await response.json();\n"
"                    \n"
"                    if (result.success) {\n"
"                        this.showSuccess('Конфігурація збережена успішно!');\n"
"                    } else {\n"
"                        this.showError('Помилка збереження конфігурації');\n"
"                    }\n"
"                    return result;\n"
"                } catch (error) {\n"
"                    this.showError('Помилка збереження конфігурації');\n"
"                }\n"
"            }\n"
"            \n"
"            updateUI(data) {\n"
"                // Оновлення метрик\n"
"                if (data.voltage !== undefined) document.getElementById('voltage').textContent = data.voltage.toFixed(1);\n"
"                if (data.current !== undefined) document.getElementById('current').textContent = data.current.toFixed(2);\n"
"                if (data.power !== undefined) document.getElementById('power').textContent = Math.round(data.power);\n"
"                if (data.energy !== undefined) document.getElementById('energy').textContent = data.energy.toFixed(2);\n"
"                \n"
"                // Оновлення прогрес-барів\n"
"                if (data.voltage !== undefined) {\n"
"                    const voltagePercent = Math.min((data.voltage / 240) * 100, 100);\n"
"                    document.getElementById('voltage-progress').style.width = voltagePercent + '%';\n"
"                }\n"
"                \n"
"                if (data.power !== undefined && data.power_limit !== undefined) {\n"
"                    const powerPercent = Math.min((data.power / data.power_limit) * 100, 100);\n"
"                    document.getElementById('power-progress').style.width = powerPercent + '%';\n"
"                }\n"
"                \n"
"                // Оновлення статусу каналів\n"
"                this.updateChannelStatus(1, data.channel1_status, data.channel1_power);\n"
"                this.updateChannelStatus(2, data.channel2_status, data.channel2_power);\n"
"            }\n"
"            \n"
"            updateChannelStatus(channelId, status, power) {\n"
"                const channelCard = document.getElementById(`channel-${channelId}`);\n"
"                const statusIndicator = channelCard.querySelector('.status-indicator');\n"
"                const statusText = document.getElementById(`status-${channelId}`);\n"
"                const powerText = document.getElementById(`power-${channelId}`);\n"
"                \n"
"                if (status === 'connected' || status === true) {\n"
"                    channelCard.className = 'channel-card connected';\n"
"                    statusIndicator.className = 'status-indicator status-on';\n"
"                    statusText.textContent = 'Підключено';\n"
"                    powerText.textContent = `${Math.round(power || 0)} Вт`;\n"
"                } else {\n"
"                    channelCard.className = 'channel-card disconnected';\n"
"                    statusIndicator.className = 'status-indicator status-off';\n"
"                    statusText.textContent = 'Відключено';\n"
"                    powerText.textContent = '0 Вт';\n"
"                }\n"
"            }\n"
"            \n"
"            showError(message) {\n"
"                this.showMessage(message, 'error');\n"
"            }\n"
"            \n"
"            showSuccess(message) {\n"
"                this.showMessage(message, 'success');\n"
"            }\n"
"            \n"
"            showMessage(message, type) {\n"
"                const messagesDiv = document.getElementById('messages');\n"
"                const messageDiv = document.createElement('div');\n"
"                messageDiv.className = type === 'error' ? 'error-message' : 'success-message';\n"
"                messageDiv.textContent = message;\n"
"                \n"
"                messagesDiv.innerHTML = '';\n"
"                messagesDiv.appendChild(messageDiv);\n"
"                \n"
"                setTimeout(() => {\n"
"                    messagesDiv.innerHTML = '';\n"
"                }, 5000);\n"
"            }\n"
"            \n"
"            startAutoUpdate() {\n"
"                setInterval(() => {\n"
"                    this.getSystemStatus();\n"
"                }, this.updateInterval);\n"
"            }\n"
"        }\n"
"        \n"
"        // Ініціалізація API\n"
"        const api = new PowerControlAPI();\n"
"        \n"
"        // Глобальні функції для кнопок\n"
"        function toggleChannel(channelId, state) {\n"
"            api.toggleChannel(channelId, state);\n"
"        }\n"
"        \n"
"        function saveSystemConfig() {\n"
"            api.savePriorityConfig();\n"
"        }\n"
"        \n"
"        function resetToDefaults() {\n"
"            document.getElementById('power-limit').value = 100;\n"
"            document.getElementById('delay-before-disconnect').value = 5;\n"
"            document.getElementById('reconnect-delay').value = 45;\n"
"            document.getElementById('device1-priority').value = 'high';\n"
"            document.getElementById('device2-priority').value = 'low';\n"
"            \n"
"            api.showSuccess('Налаштування скинуті до заводських');\n"
"        }\n"
"        \n"
"        // Початкове завантаження статусу\n"
"        api.getSystemStatus();\n"
"    </script>\n"
"</body>\n"
"</html>";


/* Start the HTTP server */
httpd_handle_t start_webserver(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();

    ESP_LOGI(TAG, "Starting HTTP server on port: %d", config.server_port);
    
    if (httpd_start(&server, &config) == ESP_OK) {
        /* URI handlers */
        httpd_uri_t root = {
            .uri       = "/",
            .method    = HTTP_GET,
            .handler   = root_get_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &root);

        httpd_uri_t led_on = {
            .uri       = "/led/on",
            .method    = HTTP_GET,
            .handler   = led_on_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &led_on);

        httpd_uri_t led_off = {
            .uri       = "/led/off",
            .method    = HTTP_GET,
            .handler   = led_off_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &led_off);
        
        return server;
    }

    ESP_LOGI(TAG, "Error starting server!");
    return NULL;
}



/* HTTP GET handler */
static esp_err_t root_get_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, HTML_PAGE, strlen(HTML_PAGE));
    return ESP_OK;
}


/* LED ON handler */
static esp_err_t led_on_handler(httpd_req_t *req)
{
    /* Here you would add code to turn on an LED */
    ESP_LOGI(TAG, "LED turned ON");
    
    /* Redirect back to the main page */
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", "/");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

/* LED OFF handler */
static esp_err_t led_off_handler(httpd_req_t *req)
{
    /* Here you would add code to turn off an LED */
    ESP_LOGI(TAG, "LED turned OFF");
    
    /* Redirect back to the main page */
    httpd_resp_set_status(req, "302 Found");
    httpd_resp_set_hdr(req, "Location", "/");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

